### ISSUE TITLE
Combine efforts with rust-nightly-nix

### ISSUE THREAD

**Issue by solson** [mozilla/nixpkgs-mozilla#15]
I haven't looked into the details yet, but it's likely that we are dealing with the same problems. I made an issue over at https://github.com/solson/rust-nightly-nix/issues/21.

**Comment by Havvy** [comment]
I think merging in rust-nightly-nix into nixpkgs-mozilla is the direction we should be going for.

**Comment by garbas** [comment]
💯 from my side, @solson would you be able to provide a PR then @nbp as current author of rust overlay (we don't want to break nobodies workflow).

Of-course you'll get a push permission with merged PR :)

And this reminds me: I need to setup binary cache for this repo.

**Comment by Ericson2314** [comment]
Well, it's not yet clear to me at least what parts form each we want :). But yes PR in the end would be good.

**Comment by garbas** [comment]
should we organize a quick google hangout to discuss how to move forward with this? ping to @solson @Ericson2314 @Havvy @nbp

**Comment by Havvy** [comment]
Most of us on the nix-nightly-rust side hang out in the Rust IRC channels (and #nixos on Freenode).

**Comment by Ericson2314** [comment]
I could do either, but I will be on vacation for about a week starting Thursday.

**Comment by nbp** [comment]
@Havvy wrote:
> I think merging in rust-nightly-nix into nixpkgs-mozilla is the direction we should be going for.

I carefully did not look too much into @solson work, because of the licensing issue.

Instead, I reversed engineered rustup and annotated the code of the the rust-overlay to take rustup as the only source of truth.

I also think this repository should be using MIT instead of the MPL, such that we can at least contribute back to Nixpkgs.

@Havvy wrote:
> Most of us on the nix-nightly-rust side hang out in the Rust IRC channels (and #nixos on Freenode).

You can find me on both freenode (pierron) and irc.mozilla.org (nbp).

**Comment by nbp** [comment]
Looking at the differences:
 - The rust overlay uses the manifest v2 like rustup, instead of the manifest v1 (deprecated?).
 - Binaries are patched by finding them, instead of listing them.
 - Uses the install script provided in the tarball instead of using rsync.
 - Provides "stable", "beta", and "nightly" like rustup, instead of only "nightly" builds.
 - The rust overlay has no equivalent to  rustcWithSysroots  function.
 - The rust overlay does not use multiple outputs.

**Comment by zimbatm** [comment]
What's the story around cross-compilation, does either support it?

**Comment by nbp** [comment]
@zimbatm , I was discussing that with @Havvy on #nixos irc.mozilla.org, and the manifest file explicitly list all rust-std targets as being inside the `rust` package, such as `wasm32-unknown-emscripten` and `x86_64-unknown-linux-musl`.

So I have not tested it, but I am confident it should work out of the box.

**Comment by Havvy** [comment]
With rust-nightly-nix, you need to use rustc-with-sysroots and list which cross-compilation targets you want to support. I have actually done this, so I know it works.

**Comment by nbp** [comment]
From what I can tell, the only missing part now seems to be the documentation of the Rust overlay.
Especially how to use it with the existing Nixpkgs infrastructure, and how to use it for cross-compiling.

**Comment by Havvy** [comment]
That matches my understanding of the situation too.

**Comment by solson** [comment]
This issue is now out of date, see https://github.com/solson/rust-nightly-nix/issues/27 for a summary of the situation.

**Comment by Ericson2314** [comment]
And for the record, cross compilation was also fixed.
